// Comprehensive list of IDX-listed stocks for autocomplete search
// All major stocks across sectors on the Indonesia Stock Exchange

export interface PopularStock {
  ticker: string; // Yahoo Finance format with .JK
  code: string; // Display code without .JK
  name: string;
  sector: string;
}

export const POPULAR_STOCKS: PopularStock[] = [
  // === PERBANKAN ===
  { ticker: "BBCA.JK", code: "BBCA", name: "Bank Central Asia", sector: "Perbankan" },
  { ticker: "BBRI.JK", code: "BBRI", name: "Bank Rakyat Indonesia", sector: "Perbankan" },
  { ticker: "BMRI.JK", code: "BMRI", name: "Bank Mandiri", sector: "Perbankan" },
  { ticker: "BBNI.JK", code: "BBNI", name: "Bank Negara Indonesia", sector: "Perbankan" },
  { ticker: "BRIS.JK", code: "BRIS", name: "Bank Syariah Indonesia", sector: "Perbankan" },
  { ticker: "BSIM.JK", code: "BSIM", name: "Bank Sinar Mas", sector: "Perbankan" },
  { ticker: "BBTN.JK", code: "BBTN", name: "Bank Tabungan Negara", sector: "Perbankan" },
  { ticker: "BJBR.JK", code: "BJBR", name: "Bank Pembangunan Daerah Jawa Barat", sector: "Perbankan" },
  { ticker: "BJTM.JK", code: "BJTM", name: "Bank Pembangunan Daerah Jatim", sector: "Perbankan" },
  { ticker: "BJB.JK", code: "BJB", name: "Bank Pembangunan Daerah Jabar Banten", sector: "Perbankan" },
  { ticker: "BDMN.JK", code: "BDMN", name: "Bank Danamon", sector: "Perbankan" },
  { ticker: "BNGA.JK", code: "BNGA", name: "Bank CIMB Niaga", sector: "Perbankan" },
  { ticker: "NISP.JK", code: "NISP", name: "Bank OCBC NISP", sector: "Perbankan" },
  { ticker: "PNBN.JK", code: "PNBN", name: "Bank Pan Indonesia", sector: "Perbankan" },
  { ticker: "MEGA.JK", code: "MEGA", name: "Bank Mega", sector: "Perbankan" },
  { ticker: "BNLI.JK", code: "BNLI", name: "Bank Permata", sector: "Perbankan" },
  { ticker: "BSWD.JK", code: "BSWD", name: "Bank Shinhan Indonesia", sector: "Perbankan" },
  { ticker: "MAYB.JK", code: "MAYB", name: "Bank Maybank Indonesia", sector: "Perbankan" },
  { ticker: "AGRO.JK", code: "AGRO", name: "Bank Agris", sector: "Perbankan" },
  { ticker: "ARTO.JK", code: "ARTO", name: "Bank Jago", sector: "Perbankan" },
  { ticker: "AMAR.JK", code: "AMAR", name: "Bank Amar Indonesia", sector: "Perbankan" },
  { ticker: "BBYB.JK", code: "BBYB", name: "Bank Neo Commerce", sector: "Perbankan" },
  { ticker: "BEKS.JK", code: "BEKS", name: "Bank Pembangunan Daerah Banten", sector: "Perbankan" },
  { ticker: "BOGA.JK", code: "BOGA", name: "Bank Oke Indonesia", sector: "Perbankan" },
  { ticker: "BACA.JK", code: "BACA", name: "Bank Capital Indonesia", sector: "Perbankan" },
  { ticker: "INPC.JK", code: "INPC", name: "Bank Ina Perdana", sector: "Perbankan" },
  { ticker: "YUPI.JK", code: "YUPI", name: "Bank Yudha Bhakti", sector: "Perbankan" },
  { ticker: "DNAR.JK", code: "DNAR", name: "Bank Oke", sector: "Perbankan" },
  { ticker: "NOBU.JK", code: "NOBU", name: "Bank Nationalnobu", sector: "Perbankan" },
  { ticker: "MCOR.JK", code: "MCOR", name: "Bank China Construction Bank", sector: "Perbankan" },
  { ticker: "BABP.JK", code: "BABP", name: "Bank MNC Internasional", sector: "Perbankan" },
  { ticker: "BINA.JK", code: "BINA", name: "Bank Ina", sector: "Perbankan" },
  { ticker: "BCIC.JK", code: "BCIC", name: "Bank JTrust Indonesia", sector: "Perbankan" },
  { ticker: "BVIC.JK", code: "BVIC", name: "Bank Victoria International", sector: "Perbankan" },
  { ticker: "BTPS.JK", code: "BTPS", name: "Bank BTPN Syariah", sector: "Perbankan" },
  { ticker: "BTPN.JK", code: "BTPN", name: "Bank BTPN", sector: "Perbankan" },
  { ticker: "BNII.JK", code: "BNII", name: "Bank Maybank Indonesia", sector: "Perbankan" },

  // === TELEKOMUNIKASI & TEKNOLOGI ===
  { ticker: "TLKM.JK", code: "TLKM", name: "Telekomunikasi Indonesia", sector: "Telekomunikasi" },
  { ticker: "ISAT.JK", code: "ISAT", name: "Indosat", sector: "Telekomunikasi" },
  { ticker: "EXCL.JK", code: "EXCL", name: "XL Axiata", sector: "Telekomunikasi" },
  { ticker: "FREN.JK", code: "FREN", name: "Smartfren Telecom", sector: "Telekomunikasi" },
  { ticker: "JAST.JK", code: "JAST", name: "Jasa Sinergi", sector: "Telekomunikasi" },
  { ticker: "GOTO.JK", code: "GOTO", name: "GoTo Gojek Tokopedia", sector: "Teknologi" },
  { ticker: "EMTK.JK", code: "EMTK", name: "Elang Mahkota Teknologi", sector: "Teknologi" },
  { ticker: "BRPT.JK", code: "BRPT", name: "Barito Pacific", sector: "Teknologi" },
  { ticker: "TPIA.JK", code: "TPIA", name: "Chandra Asri Pacific", sector: "Teknologi" },
  { ticker: "DCII.JK", code: "DCII", name: "DCI Indonesia", sector: "Teknologi" },
  { ticker: "BUKA.JK", code: "BUKA", name: "Bukalapak.com", sector: "Teknologi" },
  { ticker: "EDGE.JK", code: "EDGE", name: "Indointernet", sector: "Teknologi" },
  { ticker: "MTDL.JK", code: "MTDL", name: "Metrodata Electronics", sector: "Teknologi" },
  { ticker: "BELI.JK", code: "BELI", name: "Global Digital Niaga", sector: "Teknologi" },
  { ticker: "TFAS.JK", code: "TFAS", name: "Telefast Indonesia", sector: "Teknologi" },
  { ticker: "ATIC.JK", code: "ATIC", name: "Anabatic Technologies", sector: "Teknologi" },
  { ticker: "LMAS.JK", code: "LMAS", name: "Limas Indonesia", sector: "Teknologi" },
  { ticker: "KIOS.JK", code: "KIOS", name: "Kioson Komersial Indonesia", sector: "Teknologi" },
  { ticker: "DIVA.JK", code: "DIVA", name: "Distribusi Voucher Nusantara", sector: "Teknologi" },

  // === KONSUMER (Consumer Goods) ===
  { ticker: "UNVR.JK", code: "UNVR", name: "Unilever Indonesia", sector: "Konsumer" },
  { ticker: "ICBP.JK", code: "ICBP", name: "Indofood CBP Sukses Makmur", sector: "Konsumer" },
  { ticker: "INDF.JK", code: "INDF", name: "Indofood Sukses Makmur", sector: "Konsumer" },
  { ticker: "MYOR.JK", code: "MYOR", name: "Mayora Indah", sector: "Konsumer" },
  { ticker: "KLBF.JK", code: "KLBF", name: "Kalbe Farma", sector: "Konsumer" },
  { ticker: "SIDO.JK", code: "SIDO", name: "Industri Jamu Sido Muncul", sector: "Konsumer" },
  { ticker: "GGRM.JK", code: "GGRM", name: "Gudang Garam", sector: "Konsumer" },
  { ticker: "HMSP.JK", code: "HMSP", name: "Hanjaya Mandala Sampoerna", sector: "Konsumer" },
  { ticker: "WIIM.JK", code: "WIIM", name: "Wismilak Inti Makmur", sector: "Konsumer" },
  { ticker: "RMBA.JK", code: "RMBA", name: "Bentoel International Investama", sector: "Konsumer" },
  { ticker: "DLTA.JK", code: "DLTA", name: "Delta Djakarta", sector: "Konsumer" },
  { ticker: "ADES.JK", code: "ADES", name: "Akasha Wira International", sector: "Konsumer" },
  { ticker: "CAMP.JK", code: "CAMP", name: "Campina Ice Cream", sector: "Konsumer" },
  { ticker: "CMRP.JK", code: "CMRP", name: "Cisadane Sawit Raya", sector: "Konsumer" },
  { ticker: "CEKA.JK", code: "CEKA", name: "Wilmar Cahaya Indonesia", sector: "Konsumer" },
  { ticker: "STTP.JK", code: "STTP", name: "Siantar Top", sector: "Konsumer" },
  { ticker: "ULTJ.JK", code: "ULTJ", name: "Ultra Jaya Milk", sector: "Konsumer" },
  { ticker: "SKBM.JK", code: "SKBM", name: "Sekar Bumi", sector: "Konsumer" },
  { ticker: "SKLT.JK", code: "SKLT", name: "Sekar Laut", sector: "Konsumer" },
  { ticker: "GOOD.JK", code: "GOOD", name: "Garudafood Putra Putri", sector: "Konsumer" },
  { ticker: "HOKI.JK", code: "HOKI", name: "Buyung Poetra Sembada", sector: "Konsumer" },
  { ticker: "MLBI.JK", code: "MLBI", name: "Multi Bintang Indonesia", sector: "Konsumer" },
  { ticker: "TCID.JK", code: "TCID", name: "Mandom Indonesia", sector: "Konsumer" },
  { ticker: "MBTO.JK", code: "MBTO", name: "Martina Berto", sector: "Konsumer" },
  { ticker: "KICI.JK", code: "KICI", name: "Kedaung Indah Can", sector: "Konsumer" },
  { ticker: "IGAR.JK", code: "IGAR", name: "Champion Pacific Indonesia", sector: "Konsumer" },
  { ticker: "SOFA.JK", code: "SOFA", name: "Boston Furniture Industries", sector: "Konsumer" },
  { ticker: "WOOD.JK", code: "WOOD", name: "Integra Indocabinet", sector: "Konsumer" },
  { ticker: "HRTA.JK", code: "HRTA", name: "Hartadinata Abadi", sector: "Konsumer" },

  // Farmasi/Obat
  { ticker: "TSPC.JK", code: "TSPC", name: "Tempo Scan Pacific", sector: "Farmasi" },
  { ticker: "KAEF.JK", code: "KAEF", name: "Kimia Farma", sector: "Farmasi" },
  { ticker: "INAF.JK", code: "INAF", name: "Indofarma", sector: "Farmasi" },
  { ticker: "PYFA.JK", code: "PYFA", name: "Pyridam Farma", sector: "Farmasi" },
  { ticker: "MERK.JK", code: "MERK", name: "Merck Indonesia", sector: "Farmasi" },
  { ticker: "DVLA.JK", code: "DVLA", name: "Darya-Varia Laboratoria", sector: "Farmasi" },
  { ticker: "SCPI.JK", code: "SCPI", name: "Organon Pharma Indonesia", sector: "Farmasi" },
  { ticker: "PEHA.JK", code: "PEHA", name: "Phapros", sector: "Farmasi" },
  { ticker: "SAME.JK", code: "SAME", name: "Sarana Meditama Metropolitan", sector: "Farmasi" },
  { ticker: "MIKA.JK", code: "MIKA", name: "Mitra Internasional Keluarga", sector: "Farmasi" },
  { ticker: "HEAL.JK", code: "HEAL", name: "Medikaloka Hermina", sector: "Farmasi" },
  { ticker: "SILO.JK", code: "SILO", name: "Siloam International Hospitals", sector: "Farmasi" },
  { ticker: "PRDA.JK", code: "PRDA", name: "Prodia Widyahusada", sector: "Farmasi" },
  { ticker: "CARE.JK", code: "CARE", name: "Metro Healthcare Indonesia", sector: "Farmasi" },

  // === OTOMOTIF & KOMPONEN ===
  { ticker: "ASII.JK", code: "ASII", name: "Astra International", sector: "Otomotif" },
  { ticker: "AUTO.JK", code: "AUTO", name: "Astra Otoparts", sector: "Otomotif" },
  { ticker: "UNTR.JK", code: "UNTR", name: "United Tractors", sector: "Otomotif" },
  { ticker: "GJTL.JK", code: "GJTL", name: "Gajah Tunggal", sector: "Otomotif" },
  { ticker: "SMSM.JK", code: "SMSM", name: "Sinar Mas Multiartha", sector: "Otomotif" },
  { ticker: "INDS.JK", code: "INDS", name: "Indospring", sector: "Otomotif" },
  { ticker: "BRAM.JK", code: "BRAM", name: "Indo Kordsa", sector: "Otomotif" },
  { ticker: "IMAS.JK", code: "IMAS", name: "Indomobil Sukses Internasional", sector: "Otomotif" },
  { ticker: "NIPS.JK", code: "NIPS", name: "Nipress", sector: "Otomotif" },
  { ticker: "GDYR.JK", code: "GDYR", name: "Goodyear Indonesia", sector: "Otomotif" },
  { ticker: "BATA.JK", code: "BATA", name: "Sepatu Bata", sector: "Otomotif" },
  { ticker: "DRMA.JK", code: "DRMA", name: "Dharma Electrindo", sector: "Otomotif" },
  { ticker: "BOLT.JK", code: "BOLT", name: "Garuda Metalindo", sector: "Otomotif" },

  // === PERTAMBANGAN & ENERGI ===
  { ticker: "ANTM.JK", code: "ANTM", name: "Aneka Tambang", sector: "Pertambangan" },
  { ticker: "PTBA.JK", code: "PTBA", name: "Bukit Asam", sector: "Pertambangan" },
  { ticker: "ADRO.JK", code: "ADRO", name: "Adaro Energy Indonesia", sector: "Pertambangan" },
  { ticker: "ITMG.JK", code: "ITMG", name: "Indo Tambangraya Megah", sector: "Pertambangan" },
  { ticker: "MEDC.JK", code: "MEDC", name: "Medco Energi Internasional", sector: "Pertambangan" },
  { ticker: "INCO.JK", code: "INCO", name: "Vale Indonesia", sector: "Pertambangan" },
  { ticker: "AMMN.JK", code: "AMMN", name: "Amman Mineral", sector: "Pertambangan" },
  { ticker: "MDKA.JK", code: "MDKA", name: "Merdeka Copper Gold", sector: "Pertambangan" },
  { ticker: "HRUM.JK", code: "HRUM", name: "Harum Energy", sector: "Pertambangan" },
  { ticker: "PGAS.JK", code: "PGAS", name: "Perusahaan Gas Negara", sector: "Pertambangan" },
  { ticker: "AKRA.JK", code: "AKRA", name: "AKR Corporindo", sector: "Pertambangan" },
  { ticker: "ENRG.JK", code: "ENRG", name: "Energi Mega Persada", sector: "Pertambangan" },
  { ticker: "BUMI.JK", code: "BUMI", name: "Bumi Resources", sector: "Pertambangan" },
  { ticker: "BRMS.JK", code: "BRMS", name: "Bumi Resources Minerals", sector: "Pertambangan" },
  { ticker: "ESSA.JK", code: "ESSA", name: "Surya Esa Perkasa", sector: "Pertambangan" },
  { ticker: "ELSA.JK", code: "ELSA", name: "Elnusa", sector: "Pertambangan" },
  { ticker: "SRTG.JK", code: "SRTG", name: "Saratoga Investama Sedaya", sector: "Pertambangan" },
  { ticker: "RATU.JK", code: "RATU", name: "Ratu Prabu Energi", sector: "Pertambangan" },
  { ticker: "TOBA.JK", code: "TOBA", name: "TBS Energi Utama", sector: "Pertambangan" },
  { ticker: "ABMM.JK", code: "ABMM", name: "ABM Investama", sector: "Pertambangan" },
  { ticker: "GEMS.JK", code: "GEMS", name: "Golden Energy Mines", sector: "Pertambangan" },
  { ticker: "DOID.JK", code: "DOID", name: "Delta Dunia Makmur", sector: "Pertambangan" },
  { ticker: "KKGI.JK", code: "KKGI", name: "Resource Alam Indonesia", sector: "Pertambangan" },
  { ticker: "MCOL.JK", code: "MCOL", name: "Prima Andalan Mandiri", sector: "Pertambangan" },
  { ticker: "PKPK.JK", code: "PKPK", name: "Perdana Karya Perkasa", sector: "Pertambangan" },
  { ticker: "PSAB.JK", code: "PSAB", name: "J Resources Asia Pasifik", sector: "Pertambangan" },
  { ticker: "SMMT.JK", code: "SMMT", name: "Golden Plantation", sector: "Pertambangan" },
  { ticker: "TINS.JK", code: "TINS", name: "Timah", sector: "Pertambangan" },
  { ticker: "TKIM.JK", code: "TKIM", name: "Pabrik Kertas Tjiwi Kimia", sector: "Pertambangan" },
  { ticker: "ARII.JK", code: "ARII", name: "Atlas Resources", sector: "Pertambangan" },
  { ticker: "DEWA.JK", code: "DEWA", name: "Dewata Fortuna", sector: "Pertambangan" },
  { ticker: "GTBO.JK", code: "GTBO", name: "Garda Tujuh Buana", sector: "Pertambangan" },
  { ticker: "BOSS.JK", code: "BOSS", name: "Borneo Olah Sarana Sukses", sector: "Pertambangan" },
  { ticker: "CITA.JK", code: "CITA", name: "Cita Mineral Investindo", sector: "Pertambangan" },
  { ticker: "ZINC.JK", code: "ZINC", name: "Kapuas Prima Coal", sector: "Pertambangan" },

  // CPO / Sawit
  { ticker: "AALI.JK", code: "AALI", name: "Astra Agro Lestari", sector: "Sawit" },
  { ticker: "LSIP.JK", code: "LSIP", name: "PP London Sumatra Indonesia", sector: "Sawit" },
  { ticker: "SGRO.JK", code: "SGRO", name: "Sampoerna Agro", sector: "Sawit" },
  { ticker: "TBLA.JK", code: "TBLA", name: "Tunas Baru Lampung", sector: "Sawit" },
  { ticker: "SIMP.JK", code: "SIMP", name: "Salim Ivomas Pratama", sector: "Sawit" },
  { ticker: "TAPG.JK", code: "TAPG", name: "Triputra Agro Persada", sector: "Sawit" },
  { ticker: "SMAR.JK", code: "SMAR", name: "Sinar Mas Agro", sector: "Sawit" },
  { ticker: "CPRO.JK", code: "CPRO", name: "Central Proteina Prima", sector: "Sawit" },
  { ticker: "DSNG.JK", code: "DSNG", name: "Dharma Satya Nusantara", sector: "Sawit" },
  { ticker: "FAPA.JK", code: "FAPA", name: "Fap Agri", sector: "Sawit" },
  { ticker: "JAWA.JK", code: "JAWA", name: "Jaya Agra Wattie", sector: "Sawit" },
  { ticker: "MGRO.JK", code: "MGRO", name: "Mahkota Group", sector: "Sawit" },
  { ticker: "NSSS.JK", code: "NSSS", name: "Nusantara Sawit Sejahtera", sector: "Sawit" },
  { ticker: "PALM.JK", code: "PALM", name: "Provident Agro", sector: "Sawit" },
  { ticker: "PNGO.JK", code: "PNGO", name: "Pinago Utama", sector: "Sawit" },
  { ticker: "SSMS.JK", code: "SSMS", name: "Sawit Sumbermas Sarana", sector: "Sawit" },
  { ticker: "TRST.JK", code: "TRST", name: "Tirta Mahakam Resources", sector: "Sawit" },
  { ticker: "ANJT.JK", code: "ANJT", name: "Astra Agro Lestari (ANJT)", sector: "Sawit" },

  // === PROperti & KONSTRUKSI ===
  { ticker: "BSDE.JK", code: "BSDE", name: "Bumi Serpong Damai", sector: "Properti" },
  { ticker: "PWON.JK", code: "PWON", name: "Pakuwon Jati", sector: "Properti" },
  { ticker: "CTRA.JK", code: "CTRA", name: "Ciputra Development", sector: "Properti" },
  { ticker: "SMGR.JK", code: "SMGR", name: "Semen Indonesia", sector: "Properti" },
  { ticker: "INTP.JK", code: "INTP", name: "Indocement Tunggal Prakarsa", sector: "Properti" },
  { ticker: "LPKR.JK", code: "LPKR", name: "Lippo Karawaci", sector: "Properti" },
  { ticker: "JSMR.JK", code: "JSMR", name: "Jasa Marga", sector: "Properti" },
  { ticker: "PTPP.JK", code: "PTPP", name: "PP Persero", sector: "Properti" },
  { ticker: "WIKA.JK", code: "WIKA", name: "Wijaya Karya", sector: "Properti" },
  { ticker: "WSKT.JK", code: "WSKT", name: "Waskita Karya", sector: "Properti" },
  { ticker: "ADHI.JK", code: "ADHI", name: "Adhi Karya", sector: "Properti" },
  { ticker: "AMFG.JK", code: "AMFG", name: "Asahimas Flat Glass", sector: "Properti" },
  { ticker: "TOTL.JK", code: "TOTL", name: "Total Bangun Persada", sector: "Properti" },
  { ticker: "ACST.JK", code: "ACST", name: "Acset Indonusa", sector: "Properti" },
  { ticker: "WTON.JK", code: "WTON", name: "Wijaya Karya Beton", sector: "Properti" },
  { ticker: "PIPA.JK", code: "PIPA", name: "Multi Prima Sejahtera", sector: "Properti" },
  { ticker: "DGIK.JK", code: "DGIK", name: "Duta Graha Indah", sector: "Properti" },
  { ticker: "SSIA.JK", code: "SSIA", name: "Surya Semesta Internusa", sector: "Properti" },
  { ticker: "APLN.JK", code: "APLN", name: "Agung Podomoro Land", sector: "Properti" },
  { ticker: "ASRI.JK", code: "ASRI", name: "Alam Sutera Realty", sector: "Properti" },
  { ticker: "BKSL.JK", code: "BKSL", name: "Sentul City", sector: "Properti" },
  { ticker: "COWL.JK", code: "COWL", name: "Cowell Development", sector: "Properti" },
  { ticker: "DILD.JK", code: "DILD", name: "Intiland Development", sector: "Properti" },
  { ticker: "DMAS.JK", code: "DMAS", name: "Puradelta Lestari", sector: "Properti" },
  { ticker: "ELTY.JK", code: "ELTY", name: "Bakrieland Development", sector: "Properti" },
  { ticker: "EMDE.JK", code: "EMDE", name: "Megapolitan Developments", sector: "Properti" },
  { ticker: "GMTD.JK", code: "GMTD", name: "Gowa Makassar Tourism Development", sector: "Properti" },
  { ticker: "INDY.JK", code: "INDY", name: "Indika Energy", sector: "Properti" },
  { ticker: "KIJA.JK", code: "KIJA", name: "Kawasan Industri Jababeka", sector: "Properti" },
  { ticker: "MKPI.JK", code: "MKPI", name: "Multipolar", sector: "Properti" },
  { ticker: "MTLA.JK", code: "MTLA", name: "Metropolitan Development", sector: "Properti" },
  { ticker: "MMLP.JK", code: "MMLP", name: "Mega Manunggal Property", sector: "Properti" },
  { ticker: "MPRO.JK", code: "MPRO", name: "Maha Properti Indonesia", sector: "Properti" },
  { ticker: "MTMH.JK", code: "MTMH", name: "MNC Tourism", sector: "Properti" },
  { ticker: "NASA.JK", code: "NASA", name: "Andalan Sakti Prima", sector: "Properti" },
  { ticker: "NRCA.JK", code: "NRCA", name: "Nusa Raya Cipta", sector: "Properti" },
  { ticker: "PBRX.JK", code: "PBRX", name: "Pan Brothers", sector: "Properti" },
  { ticker: "PLIN.JK", code: "PLIN", name: "Plaza Indonesia Realty", sector: "Properti" },
  { ticker: "PPRO.JK", code: "PPRO", name: "PP Properti", sector: "Properti" },
  { ticker: "RBMS.JK", code: "RBMS", name: "Ristia Bintang Mahkotasejati", sector: "Properti" },
  { ticker: "RIMO.JK", code: "RIMO", name: "Royalindo Investama", sector: "Properti" },
  { ticker: "RODA.JK", code: "RODA", name: "Pikko Land Development", sector: "Properti" },
  { ticker: "SMDM.JK", code: "SMDM", name: "Suryamas Dutamakmur", sector: "Properti" },
  { ticker: "TARA.JK", code: "TARA", name: "Tara Citra Nusantara", sector: "Properti" },
  { ticker: "TRIN.JK", code: "TRIN", name: "Perintis Triniti Properti", sector: "Properti" },

  // === INFRASTRUKTUR & TRANSPORTASI ===
  { ticker: "ASSA.JK", code: "ASSA", name: "Adi Sarana Armada", sector: "Transportasi" },
  { ticker: "BIRD.JK", code: "BIRD", name: "Blue Bird", sector: "Transportasi" },
  { ticker: "GIAA.JK", code: "GIAA", name: "Garuda Indonesia", sector: "Transportasi" },
  { ticker: "INDX.JK", code: "INDX", name: "Tanah Laut", sector: "Transportasi" },
  { ticker: "KARW.JK", code: "KARW", name: "Ictsi Jasa Prima", sector: "Transportasi" },
  { ticker: "MIRA.JK", code: "MIRA", name: "Mitra International Resources", sector: "Transportasi" },
  { ticker: "LRNA.JK", code: "LRNA", name: "Eka Sari Lorena", sector: "Transportasi" },
  { ticker: "SMDR.JK", code: "SMDR", name: "Samudera Indonesia", sector: "Transportasi" },
  { ticker: "TAXI.JK", code: "TAXI", name: "Express Transindo Utama", sector: "Transportasi" },
  { ticker: "TMAS.JK", code: "TMAS", name: "Pelayaran Tempuran Emas", sector: "Transportasi" },
  { ticker: "TPMA.JK", code: "TPMA", name: "Trans Power Marine", sector: "Transportasi" },
  { ticker: "WINS.JK", code: "WINS", name: "Wintermar Offshore Marine", sector: "Transportasi" },
  { ticker: "SHIP.JK", code: "SHIP", name: "Sillo Maritime Perdana", sector: "Transportasi" },
  { ticker: "SOCI.JK", code: "SOCI", name: "Soechi Lines", sector: "Transportasi" },
  { ticker: "TRAM.JK", code: "TRAM", name: "Trada Alam Minera", sector: "Transportasi" },
  { ticker: "HATM.JK", code: "HATM", name: "Hasta Mulia", sector: "Transportasi" },
  { ticker: "DEAL.JK", code: "DEAL", name: "Dewata Freightinternational", sector: "Transportasi" },
  { ticker: "CMPP.JK", code: "CMPP", name: "AirAsia Indonesia", sector: "Transportasi" },
  { ticker: "IATA.JK", code: "IATA", name: "Indonesia Transport", sector: "Transportasi" },
  { ticker: "JAYA.JK", code: "JAYA", name: "Armada Berjaya Trans", sector: "Transportasi" },

  // === RITEL & DISTRIBUSI ===
  { ticker: "MAPI.JK", code: "MAPI", name: "Mitra Adiperkasa", sector: "Ritel" },
  { ticker: "ACES.JK", code: "ACES", name: "Ace Hardware Indonesia", sector: "Ritel" },
  { ticker: "LPPF.JK", code: "LPPF", name: "Matahari Department Store", sector: "Ritel" },
  { ticker: "AMRT.JK", code: "AMRT", name: "Sumber Alfaria Trijaya", sector: "Ritel" },
  { ticker: "RALS.JK", code: "RALS", name: "Ramayana Lestari Sentosa", sector: "Ritel" },  { ticker: "HERO.JK", code: "HERO", name: "Hero Supermarket", sector: "Ritel" },
  { ticker: "GELA.JK", code: "GELA", name: "Golden Retailindo", sector: "Ritel" },
  { ticker: "KOIN.JK", code: "KOIN", name: "Kokoh Inti Arebama", sector: "Ritel" },
  { ticker: "MIDI.JK", code: "MIDI", name: "Midi Utama Indonesia", sector: "Ritel" },
  { ticker: "MCAS.JK", code: "MCAS", name: "M CASH Integrasi", sector: "Ritel" },
  { ticker: "DIVA.JK", code: "DIVA", name: "Distribusi Voucher Nusantara", sector: "Ritel" },
  { ticker: "CSAP.JK", code: "CSAP", name: "Catur Sentosa Adiprana", sector: "Ritel" },
  { ticker: "ERAA.JK", code: "ERAA", name: "Erajaya Swasembada", sector: "Ritel" },
  { ticker: "BHIT.JK", code: "BHIT", name: "Bhakti Investama", sector: "Ritel" },
  { ticker: "MPPA.JK", code: "MPPA", name: "Matahari Putra Prima", sector: "Ritel" },
  { ticker: "EPMT.JK", code: "EPMT", name: "Enseval Putera Megatrading", sector: "Ritel" },
  { ticker: "MDKA.JK", code: "MDKA", name: "Merdeka Copper Gold", sector: "Ritel" },

  // === MANUFAKTUR ===
  { ticker: "INAI.JK", code: "INAI", name: "Indal Aluminium Industry", sector: "Manufaktur" },
  { ticker: "ISSP.JK", code: "ISSP", name: "Steel Pipe Industry", sector: "Manufaktur" },
  { ticker: "KRAS.JK", code: "KRAS", name: "Krakatau Steel", sector: "Manufaktur" },
  { ticker: "NIKL.JK", code: "NIKL", name: "Pelat Timah Nusantara", sector: "Manufaktur" },
  { ticker: "CTBN.JK", code: "CTBN", name: "Citra Tubindo", sector: "Manufaktur" },
  { ticker: "BRPT.JK", code: "BRPT", name: "Barito Pacific", sector: "Manufaktur" },
  { ticker: "TPIA.JK", code: "TPIA", name: "Chandra Asri Pacific", sector: "Manufaktur" },
  { ticker: "BRNA.JK", code: "BRNA", name: "Berlina", sector: "Manufaktur" },
  { ticker: "DPNS.JK", code: "DPNS", name: "Dharma Persada", sector: "Manufaktur" },
  { ticker: "IKAI.JK", code: "IKAI", name: "Intikeramik Alamasri Industri", sector: "Manufaktur" },
  { ticker: "KBLI.JK", code: "KBLI", name: "KMI Wire and Cable", sector: "Manufaktur" },
  { ticker: "KBLM.JK", code: "KBLM", name: "Kabelindo Murni", sector: "Manufaktur" },
  { ticker: "LION.JK", code: "LION", name: "Lion Metal Works", sector: "Manufaktur" },
  { ticker: "LMPI.JK", code: "LMPI", name: "Langgeng Makmur Industri", sector: "Manufaktur" },
  { ticker: "MARK.JK", code: "MARK", name: "Mark Dynamics Indonesia", sector: "Manufaktur" },
  { ticker: "MYTX.JK", code: "MYTX", name: "Asia Pacific Textile", sector: "Manufaktur" },
  { ticker: "PICO.JK", code: "PICO", name: "Pelangi Indah Canindo", sector: "Manufaktur" },
  { ticker: "POLY.JK", code: "POLY", name: "Asia Pacific Fibers", sector: "Manufaktur" },
  { ticker: "RICY.JK", code: "RICY", name: "Ricky Putra Globalindo", sector: "Manufaktur" },
  { ticker: "SBAT.JK", code: "SBAT", name: "Seahouse Aneka Industri", sector: "Manufaktur" },
  { ticker: "SSTM.JK", code: "SSTM", name: "Sunson Textile Manufacturer", sector: "Manufaktur" },
  { ticker: "STAR.JK", code: "STAR", name: "Star Petrochem", sector: "Manufaktur" },
  { ticker: "TALF.JK", code: "TALF", name: "Tunas Alfin", sector: "Manufaktur" },
  { ticker: "TFCO.JK", code: "TFCO", name: "Tifico Fiber Indonesia", sector: "Manufaktur" },
  { ticker: "TRIS.JK", code: "TRIS", name: "Trisula International", sector: "Manufaktur" },
  { ticker: "UNIT.JK", code: "UNIT", name: "Nusantara Inti Corpora", sector: "Manufaktur" },
  { ticker: "VOKS.JK", code: "VOKS", name: "Voksel Electric", sector: "Manufaktur" },
  { ticker: "YPAS.JK", code: "YPAS", name: "Yanaprima Hastapersada", sector: "Manufaktur" },
  { ticker: "AMIN.JK", code: "AMIN", name: "Ateliers Mecaniques D Indonesie", sector: "Manufaktur" },
  { ticker: "ARGO.JK", code: "ARGO", name: "Argo Manunggal Group", sector: "Manufaktur" },
  { ticker: "ASII.JK", code: "ASII", name: "Astra International", sector: "Manufaktur" },
  { ticker: "BAJA.JK", code: "BAJA", name: "Saranacentral Bajatama", sector: "Manufaktur" },
  { ticker: "BRAM.JK", code: "BRAM", name: "Indo Kordsa", sector: "Manufaktur" },
  { ticker: "CINT.JK", code: "CINT", name: "Chandra Investment", sector: "Manufaktur" },
  { ticker: "CLPI.JK", code: "CLPI", name: "Colorpark Indonesia", sector: "Manufaktur" },
  { ticker: "DNKS.JK", code: "DNKS", name: "Dian Ketapang Sentosa", sector: "Manufaktur" },
  { ticker: "EKAD.JK", code: "EKAD", name: "Ekadharma International", sector: "Manufaktur" },
  { ticker: "ERTX.JK", code: "ERTX", name: "Eratex Daja Pratama", sector: "Manufaktur" },
  { ticker: "ESSA.JK", code: "ESSA", name: "Surya Esa Perkasa", sector: "Manufaktur" },
  { ticker: "ESTI.JK", code: "ESTI", name: "Ever Shine Textile", sector: "Manufaktur" },
  { ticker: "FPNI.JK", code: "FPNI", name: "FPN Property Development", sector: "Manufaktur" },
  { ticker: "GDST.JK", code: "GDST", name: "Gunawan Dianjaya Steel", sector: "Manufaktur" },
  { ticker: "GGRM.JK", code: "GGRM", name: "Gudang Garam", sector: "Manufaktur" },
  { ticker: "IFII.JK", code: "IFII", name: "Indonesia Fibreboard", sector: "Manufaktur" },
  { ticker: "IMPC.JK", code: "IMPC", name: "Impack Pratama Industri", sector: "Manufaktur" },
  { ticker: "INCI.JK", code: "INCI", name: "Intanwijaya Internasional", sector: "Manufaktur" },
  { ticker: "INRU.JK", code: "INRU", name: "Toba Pulp Lestari", sector: "Manufaktur" },
  { ticker: "IPOL.JK", code: "IPOL", name: "Indopoly Swakarsa Industry", sector: "Manufaktur" },
  { ticker: "ISP.JK", code: "ISP", name: "Andira Agro", sector: "Manufaktur" },
  { ticker: "JPRS.JK", code: "JPRS", name: "Jaya Pari Steel", sector: "Manufaktur" },
  { ticker: "JTPE.JK", code: "JTPE", name: "Jasuindo Tiga Perkasa", sector: "Manufaktur" },

  // === KEUANGAN (Non-Bank) ===
  { ticker: "ADMF.JK", code: "ADMF", name: "Adira Dinamika Multi Finance", sector: "Keuangan" },
  { ticker: "BFIN.JK", code: "BFIN", name: "BFI Finance Indonesia", sector: "Keuangan" },
  { ticker: "BBHI.JK", code: "BBHI", name: "Bank Harda Internasional (closed)", sector: "Keuangan" },
  { ticker: "CFIN.JK", code: "CFIN", name: "Mandala Multifinance", sector: "Keuangan" },
  { ticker: "FINN.JK", code: "FINN", name: "First Indo American Leasing", sector: "Keuangan" },
  { ticker: "IMFI.JK", code: "IMFI", name: "Indomitra Multi Finance", sector: "Keuangan" },
  { ticker: "MFIN.JK", code: "MFIN", name: "Mandala Multifinance (MFIN)", sector: "Keuangan" },
  { ticker: "PNIN.JK", code: "PNIN", name: "Panin Insurance", sector: "Keuangan" },
  { ticker: "PNLF.JK", code: "PNLF", name: "Panin Financial", sector: "Keuangan" },
  { ticker: "TIFA.JK", code: "TIFA", name: "Tifa Finance", sector: "Keuangan" },
  { ticker: "VRNA.JK", code: "VRNA", name: "Mizuho Leasing Indonesia", sector: "Keuangan" },
  { ticker: "WOMF.JK", code: "WOMF", name: "Wahana Ottomitra Multiartha", sector: "Keuangan" },
  { ticker: "YULE.JK", code: "YULE", name: "Yulie Sekuritas Indonesia", sector: "Keuangan" },

  // Asuransi
  { ticker: "ABDA.JK", code: "ABDA", name: "Asuransi Bina Dana Arta", sector: "Asuransi" },
  { ticker: "AHAP.JK", code: "AHAP", name: "Asuransi Harta Aman Pratama", sector: "Asuransi" },
  { ticker: "AMAG.JK", code: "AMAG", name: "Asuransi Multi Artha Guna", sector: "Asuransi" },
  { ticker: "ASBI.JK", code: "ASBI", name: "Asuransi Bintang", sector: "Asuransi" },
  { ticker: "ASDM.JK", code: "ASDM", name: "Asuransi Dayin Mitra", sector: "Asuransi" },
  { ticker: "ASII.JK", code: "ASII", name: "Astra International (Asuransi)", sector: "Asuransi" },
  { ticker: "ASJT.JK", code: "ASJT", name: "Asuransi Jasa Tania", sector: "Asuransi" },
  { ticker: "ASRM.JK", code: "ASRM", name: "Asuransi Ramayana", sector: "Asuransi" },
  { ticker: "ASS.JK", code: "ASS", name: "Askrindo", sector: "Asuransi" },
  { ticker: "LIFE.JK", code: "LIFE", name: "Asuransi Jiwa Sinarmas MSIG", sector: "Asuransi" },
  { ticker: "LPLI.JK", code: "LPLI", name: "Lippo E-Net", sector: "Asuransi" },
  { ticker: "MREI.JK", code: "MREI", name: "Maskapai Reasuransi Indonesia", sector: "Asuransi" },
  { ticker: "MTWI.JK", code: "MTWI", name: "Mitra Transaksi Indonesia", sector: "Asuransi" },
  { ticker: "PDES.JK", code: "PDES", name: "Destinasi Tirta Lestari", sector: "Asuransi" },
  { ticker: "PNIN.JK", code: "PNIN", name: "Panin Insurance", sector: "Asuransi" },

  // Sekuritas
  { ticker: "PANS.JK", code: "PANS", name: "Panin Sekuritas", sector: "Sekuritas" },
  { ticker: "PEGE.JK", code: "PEGE", name: "Panca Global Sekuritas", sector: "Sekuritas" },
  { ticker: "TRIM.JK", code: "TRIM", name: "Trimegah Sekuritas", sector: "Sekuritas" },
  { ticker: "YULE.JK", code: "YULE", name: "Yulie Sekuritas Indonesia", sector: "Sekuritas" },

  // === INVESTMENT HOLDING ===
  { ticker: "ABMM.JK", code: "ABMM", name: "ABM Investama", sector: "Holding" },
  { ticker: "BHIT.JK", code: "BHIT", name: "Bhakti Investama", sector: "Holding" },
  { ticker: "BMTR.JK", code: "BMTR", name: "Global Mediacom", sector: "Holding" },
  { ticker: "BNBR.JK", code: "BNBR", name: "Bakrie & Brothers", sector: "Holding" },
  { ticker: "BVIC.JK", code: "BVIC", name: "Bank Victoria International", sector: "Holding" },
  { ticker: "CANI.JK", code: "CANI", name: "Cans Nusantara", sector: "Holding" },
  { ticker: "CARS.JK", code: "CARS", name: "Tifa Internasional", sector: "Holding" },
  { ticker: "DAAZ.JK", code: "DAAZ", name: "Daaz Bara Lestari", sector: "Holding" },
  { ticker: "DGNS.JK", code: "DGNS", name: "Dharma Guna Nusantara", sector: "Holding" },
  { ticker: "FIPP.JK", code: "FIPP", name: "First Pacific Plant", sector: "Holding" },
  { ticker: "HITS.JK", code: "HITS", name: "Humpuss Intermoda Transportasi", sector: "Holding" },
  { ticker: "IOTF.JK", code: "IOTF", name: "Steel Development", sector: "Holding" },
  { ticker: "JTEN.JK", code: "JTEN", name: "Jasa Tenaga", sector: "Holding" },
  { ticker: "KIAS.JK", code: "KIAS", name: "Keramika Indonesia Assosiasi", sector: "Holding" },
  { ticker: "LPPS.JK", code: "LPPS", name: "Lenox Pasifik Investama", sector: "Holding" },
  { ticker: "MASA.JK", code: "MASA", name: "Multistrada Arah Sarana", sector: "Holding" },
  { ticker: "MINA.JK", code: "MINA", name: "Sanurhasta Mitra", sector: "Holding" },
  { ticker: "OCAP.JK", code: "OCAP", name: "Onix Capital", sector: "Holding" },
  { ticker: "PADI.JK", code: "PADI", name: "Minna Padi Investama", sector: "Holding" },
  { ticker: "POLA.JK", code: "POLA", name: "Polaris Investama", sector: "Holding" },
  { ticker: "POOL.JK", code: "POOL", name: "Pool Advista Indonesia", sector: "Holding" },
  { ticker: "PRAS.JK", code: "PRAS", name: "Prima Alloy Steel Universal", sector: "Holding" },
  { ticker: "PSKT.JK", code: "PSKT", name: "Pusaka Kreasi Mandiri", sector: "Holding" },
  { ticker: "PTRO.JK", code: "PTRO", name: "Petrosea", sector: "Holding" },
  { ticker: "PWON.JK", code: "PWON", name: "Pakuwon Jati (Holding)", sector: "Holding" },
  { ticker: "RIGS.JK", code: "RIGS", name: "Rig Tenders Indonesia", sector: "Holding" },
  { ticker: "SDPC.JK", code: "SDPC", name: "Millennium Pharmacon International", sector: "Holding" },
  { ticker: "SPMA.JK", code: "SPMA", name: "Suparma", sector: "Holding" },
  { ticker: "SRIL.JK", code: "SRIL", name: "Sri Rejeki Isman", sector: "Holding" },
  { ticker: "TAPG.JK", code: "TAPG", name: "Triputra Agro Persada", sector: "Holding" },
  { ticker: "TINS.JK", code: "TINS", name: "Timah (Holding)", sector: "Holding" },
  { ticker: "TIRA.JK", code: "TIRA", name: "Tira Austenite", sector: "Holding" },
  { ticker: "TOTO.JK", code: "TOTO", name: "Surya Toto Indonesia", sector: "Holding" },
  { ticker: "TRIL.JK", code: "TRIL", name: "Triwira Insanlestari", sector: "Holding" },
  { ticker: "TURI.JK", code: "TURI", name: "Tunas Ridean", sector: "Holding" },
  { ticker: "UCID.JK", code: "UCID", name: "United Chemical Intersentosa", sector: "Holding" },
  { ticker: "VINS.JK", code: "VINS", name: "Multi Vinayaka", sector: "Holding" },
  { ticker: "WAPO.JK", code: "WAPO", name: "Wahana Pronatural", sector: "Holding" },
  { ticker: "WEHA.JK", code: "WEHA", name: "Panorama Hospitality", sector: "Holding" },
  { ticker: "WINR.JK", code: "WINR", name: "Winner Nusantara Jaya", sector: "Holding" },
  { ticker: "WOMF.JK", code: "WOMF", name: "Wahana Ottomitra Multiartha", sector: "Holding" },
  { ticker: "YAKW.JK", code: "YAKW", name: "Yakin Buana", sector: "Holding" },
  { ticker: "YPAS.JK", code: "YPAS", name: "Yanaprima Hastapersada", sector: "Holding" },

  // === LOGISTIK & TRADE ===
  { ticker: "AKRA.JK", code: "AKRA", name: "AKR Corporindo", sector: "Logistik" },
  { ticker: "HEXA.JK", code: "HEXA", name: "Hexindo Adiperkasa", sector: "Logistik" },
  { ticker: "MTFN.JK", code: "MTFN", name: "Metropolitan Transf", sector: "Logistik" },
  { ticker: "RUP.JK", code: "RUP", name: "Rukun Raharja", sector: "Logistik" },
  { ticker: "TPIC.JK", code: "TPIC", name: "Mitra Investama", sector: "Logistik" },
  { ticker: "TIRA.JK", code: "TIRA", name: "Tira Austenite", sector: "Logistik" },
  { ticker: "TRUK.JK", code: "TRUK", name: "Guna Timur Raya", sector: "Logistik" },
  { ticker: "WEGE.JK", code: "WEGE", name: "Wijaya Karya Bangunan Gedung", sector: "Logistik" },
  { ticker: "GPRA.JK", code: "GPRA", name: "Perdana Gapuraprima", sector: "Logistik" },

  // === MEDIA & TELEKOMUNIKASI LAINNYA ===
  { ticker: "MNCN.JK", code: "MNCN", name: "Media Nusantara Citra", sector: "Media" },
  { ticker: "SCMA.JK", code: "SCMA", name: "Surya Citra Media", sector: "Media" },
  { ticker: "VIVA.JK", code: "VIVA", name: "Visi Media Asia", sector: "Media" },
  { ticker: "TMPO.JK", code: "TMPO", name: "Tempo Intimedia", sector: "Media" },
  { ticker: "KOE.JK", code: "KOE", name: "Kokoh Exa Nusantara", sector: "Media" },
  { ticker: "ITAN.JK", code: "ITAN", name: "Itanagara Transindo", sector: "Media" },

  // === PERIKANAN & PERTANIAN ===
  { ticker: "CPRO.JK", code: "CPRO", name: "Central Proteina Prima", sector: "Perikanan" },
  { ticker: "MAIN.JK", code: "MAIN", name: "Malindo Feedmill", sector: "Pertanian" },
  { ticker: "CPIN.JK", code: "CPIN", name: "Charoen Pokphand Indonesia", sector: "Pertanian" },
  { ticker: "JPFA.JK", code: "JPFA", name: "Jaya Agro Investama", sector: "Pertanian" },
  { ticker: "SIPD.JK", code: "SIPD", name: "Sierad Produce", sector: "Pertanian" },
  { ticker: "SIMP.JK", code: "SIMP", name: "Salim Ivomas Pratama (Pertanian)", sector: "Pertanian" },
  { ticker: "TAPG.JK", code: "TAPG", name: "Triputra Agro Persada (TAPG)", sector: "Pertanian" },
  { ticker: "ANDI.JK", code: "ANDI", name: "Andira Agro (Pertanian)", sector: "Pertanian" },
  { ticker: "DSFI.JK", code: "DSFI", name: "Dharma Samudera Fishing Industries", sector: "Perikanan" },
  { ticker: "PSDN.JK", code: "PSDN", name: "Prasidha Indonesian Sejahtera", sector: "Pertanian" },
  { ticker: "STAA.JK", code: "STAA", name: "Sumber Tani Agung Resources", sector: "Pertanian" },

  // === KONSTRUKSI LAINNYA ===
  { ticker: "ACST.JK", code: "ACST", name: "Acset Indonusa", sector: "Konstruksi" },
  { ticker: "KOBX.JK", code: "KOBX", name: "Kobexindo Tractors", sector: "Konstruksi" },
  { ticker: "NRCA.JK", code: "NRCA", name: "Nusa Raya Cipta", sector: "Konstruksi" },
  { ticker: "TOTL.JK", code: "TOTL", name: "Total Bangun Persada", sector: "Konstruksi" },
  { ticker: "PTDU.JK", code: "PTDU", name: "Djasa Ubersakti", sector: "Konstruksi" },
  { ticker: "CSIS.JK", code: "CSIS", name: "Cipta Srigati Lestari", sector: "Konstruksi" },
];

export function getStockByCode(code: string): PopularStock | undefined {
  const normalized = code.toUpperCase().replace(".JK", "");
  return POPULAR_STOCKS.find((s) => s.code === normalized);
}

export function getStocksBySector(): Record<string, PopularStock[]> {
  return POPULAR_STOCKS.reduce(
    (acc, stock) => {
      const sector = stock.sector || "Lainnya";
      if (!acc[sector]) acc[sector] = [];
      acc[sector].push(stock);
      return acc;
    },
    {} as Record<string, PopularStock[]>,
  );
}

export const SECTORS = Array.from(
  new Set(POPULAR_STOCKS.map((s) => s.sector).filter(Boolean)),
).sort();
